config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
      resources :comments, only: :create
      resources :photos, only: :create
  end

  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver_now
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @places = Place.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merienda&display=swap" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-dark bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
             &nbsp; New Place
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="places-box col-10 offset-1">
  <h1>Edit Your Place</h1>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<h1 class="pagetitle col-10 offset-1">Nomster by Alice</h1>
<br />

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Find the best places on Columbia Pike!</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Great places to go out to eat!</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Find the best places on Columbia Pike!</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br />

<% @places.each do |place| %>
  <div class="places-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p>

    <% if place.user.present? %>
      <small><%= place.user.email %></small>

      <% if place.comments.present? %>
        <div class="col-12">
          <blockquote class="commentbox">
            <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> &nbsp; - &nbsp; &nbsp;
                <%= place.comments.last.message %> 
                <br />
            -- &nbsp; <small><%= place.comments.last.user.email %></small>
            <% end %>

          </blockquote>
        </div>
      <% end %>
      
    <% end %>
  </div>

<% end %>
<div class="pagetitle col-10 offset-1">
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    
    <%= will_paginate @posts, :container => false %>
    
</div>
</div>

app/views/places/new.html.erb
<h1 class="pagetitle col-10 offset-1">Enter Your Place Details</h1>

<div class="places-box col-10 offset-1">

<%= simple_form_for @place do |f| %>
  <%= f.input :name, :label => 'Name:' %>
  <%= f.input :address, :label => 'Address:' %>
  <%= f.input :description, :label => "What's it like?" %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>

<% end %>

</div>

app/views/places/show.html.erb
<div class="places-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>

  <br />

  <% if @place.latitude.present? && @place.longitude.present? %>
  
   <script>
      var myLatLng = {lat:  <%= @place.latitude %>, lng: <%= @place.longitude %>}
      
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          zoom: 16,
        });

        var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }


    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_ChmCk8TWX3I9jonXSSX_qnilNPJGN9s&callback=initMap"
    async defer></script>

    <div id="map"></div>
  <% end %>

  <br />

  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>
  <br />
</div>
<div class="clear"></div>

  <!-- Button trigger modal -->
<div class="col-10 offset-1" name="ButtonRows">
  <button type="button" class="btn btn-primary btn-lg col-2" data-toggle="modal" data-target="#myModal">
    Add Comment
  </button>
  &nbsp &nbsp
  <button type="button" class="btn btn-primary btn-lg col-2" data-toggle="modal" data-target="#photoModal">
    Add Photo
  </button>
</div>

<div class="clear"></div>

<!-- Modal - Comments -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
      <div class="modal-body">
        <div class="places-box col-10 offset-1">
            <%= f.input :rating, as: :select, collection: Comment::RATINGS,:label => 'Rate me!'%>
            <%= f.input :message, :label => 'Comment:' %>
            <br />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal - Photos -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myPhotoLabel">Add a Photo</h4>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |photo| %>
      <div class="modal-body">
        <div class="places-box col-10 offset-1">
            <%= photo.input :picture %>
            <%= photo.input :caption, :label => 'Photo Caption: '%>
            <br />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= photo.submit "Add a photo", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

  <h1 class= "pagetitle">Comments</h1>
  <br />
  <div class="containter">
  <div class="row">
  <% @place.comments.each do |comment| %>
  <div class="col-12 col-sm-6">
    <blockquote class="commentbox">
      <b><%= comment.humanized_rating %></b> &nbsp; - &nbsp; &nbsp;
          <%= comment.message %> 
          <br />
      -- &nbsp; <small><%= comment.user.email %></small>
    </blockquote>
  </div>
  <% end %>
</div>
</div>


<h1 class= "pagetitle">Photos</h1>
  <br />
  <div class="containter">
  <div class="row">
  <% @place.photos.each do |photo| %>
  <div class="col-12 col-sm-6">
    <blockquote class="commentbox">
      <%=image_tag photo.picture.url, :class => "placephoto col-5 col-sm-5" %>
      <br />
      <b><%= photo.caption %></b> 
          <br />
      -- &nbsp; <small><%= photo.user.email %></small>
    </blockquote>
  </div>
  <% end %>
</div>
</div>
  

app/views/users/show.html.erb
<div class="containter stats-box col-10 offset-1">
  <div class="row">
    <div class="userheader col-4">
      <%= image_tag 'user.png', class:"userimage" %>
      <h3 class="pagetitle"><%= @user.email %></h3>
    </div>

    <div class="userstats col-8">
      <h5 class="subtitle">
        Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h5>
      <hr />
      <div class="containter">
          <h6 class="subtitle"><%= @user.comments.count %> &nbsp total comments &nbsp &nbsp | &nbsp &nbsp
          <%= @user.comments.where(rating: '5_stars').count %> &nbsp 5 star reviews</h6>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>
<hr />
<br />


<div class="usercomments">
  <h1 class="text-center">My Comments</h1>
  <br />
  <div class="containter">
    <div class="row">
      <% @user.comments.each do |comment| %>
      <div class="col-12 col-sm-6">
        <blockquote class="commentbox">
          <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
          <b><%= comment.humanized_rating %></b> &nbsp; - &nbsp; &nbsp;
              <%= comment.message %> 
              <br />
          -- &nbsp; <small><%= comment.user.email %></small>
        </blockquote>
      </div>
      <% end %>
    </div>
  </div>
</div>



<% @user.places.each do |place| %>
  <div class="places-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p>

    <% if place.user.present? %>
      <small><%= place.user.email %></small>

      <% if place.comments.present? %>
        <div class="col-12">
          <blockquote class="commentbox">
            <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> &nbsp; - &nbsp; &nbsp;
                <%= place.comments.last.message %> 
                <br />
            -- &nbsp; <small><%= place.comments.last.user.email %></small>
            <% end %>

          </blockquote>
        </div>
      <% end %>
      
    <% end %>
  </div>

<% end %>
  